### ISSUE TITLE
Credit Original Author

### ISSUE THREAD

**Issue by tnightengale** [snowplow-devops/terraform-google-bigquery-loader-pubsub-ce#11]
Hey @jbeemster ,

I recently became aware of this module in a discussion during an interview. The interviewer looking at my Github and [my older module](https://github.com/tnightengale/snowplow-terraform-google-big-query-loader-ce/tree/main?tab=readme-ov-file) questioned the source of this module. 

The implication was that I made my own module rather than work within Snowplow's open source ecosystem. 

A worse misunderstanding for my professional reputation might be that I copied this module.

Glancing at this module, it does seem like the initial commits are incredibly similar to my module. I know we spoke back in late 2022 about moving my module under the official Snowplow DevOps org and I didn't stay on top of the extended request to sign a contributor license agreement.

If indeed you proceeded with using sections of my module would you mind crediting that in some way on this project? I would like to archive my older module, as obviously this is the official version, and is actively maintained. However, it would be nice to have my efforts recognized.

Thanks,

Teghan

<img width="1512" alt="Screenshot 2024-08-19 at 4 19 42 PM" src="https://github.com/user-attachments/assets/c562db57-6bcc-4672-8ccf-6c2590b0afb2">
![Screenshot 2024-08-19 at 4 19 42 PM (2)](https://github.com/user-attachments/assets/af442bfa-a732-471a-a5f8-365b6b0d8739)

**Comment by jbeemster** [comment]
Hi @tnightengale have added a PR here if this works for you?
https://github.com/snowplow-devops/terraform-google-bigquery-loader-pubsub-ce/pull/12

The CLA details are here if you could please sign them and then ill get that notice merged in: https://docs.snowplow.io/docs/contributing/contributor-license-agreement/

**Comment by tnightengale** [comment]
Thanks @jbeemster!

And thank you for adopting and improving the initial work!

#12 lgtm, but would you mind approving the suggested change so I will appear as a contributor to this project?

**Comment by tnightengale** [comment]
Also, I have signed the CLA.

<img width="518" alt="Screenshot 2024-08-21 at 9 31 06 AM" src="https://github.com/user-attachments/assets/72abf9d7-c3a7-4bd9-a67b-4b34a4cf6ed5">
